spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enrick-skill?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: "classpath:com.springboot.core.repository/*.xml"
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
  #    java:
  #      sql: DEBUG
  #    org:
  #      mybatis: DEBUG
  #      apache:
  #        ibatis: DEBUG
    core.repository: DEBUG